name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade flit
        flit install --deps=all
    - name: Type check
      run: mypy heroku_audit stubs
    - name: Format
      run: black --check heroku_audit stubs
    - name: lint
      run: ruff check heroku_audit stubs

  build:
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Publish to PyPi
      if: ${{ github.ref_type == 'tag' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print_hash: true
