name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: python -m pip install .

  build:
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install .
    - name: Build package
      run: |
        flit build
    - name: Save built package
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: |
          dist
    - name: Publish to PyPi
      if: ${{ github.ref_type == 'tag' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print_hash: true
